apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: docker-php
          image: gcr.io/testing-purpose-251911/docker-php:v1
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"